### ISSUE TITLE
Link to License on Nuget is wrong

### ISSUE THREAD

**Issue by noo7** [CoreCompat/libgdiplus-packaging#6]
On Nuget, the page for the package: https://www.nuget.org/packages/runtime.osx.10.10-x64.CoreCompat.System.Drawing has a wrong link: https://raw.githubusercontent.com/CoreCompat/libgdiplus-packaging/LICENSE
It can cause Liecense Scanning software to report the component as a risky component to intergarte from a legal perspective.

**Comment by qmfrederik** [comment]
This has been fixed a while ago.
