### ISSUE TITLE
Nuget package for linux 

### ISSUE THREAD

**Issue by jonathanantoine** [CoreCompat/libgdiplus-packaging#7]
Hello,

Would it be possible to get a nuget package for linux platforms ?
That would be nice for environments where we can't do an apt-get install (azure functions, etc.).

Regards.

**Comment by qmfrederik** [comment]
I don't have any plans for that at the moment. The problem with libgdiplus on Linux is that it has a fair number of dependencies (e.g. libpng, libjpeg,...), and making a libgdiplus package which contains the correct version of these dependencies for the various Linux distrubtions gets messy, quickly.

**Comment by jonathanantoine** [comment]
Thanks for answering. Can you maybe give me some hints so I would be able to do it myself for Azure Functions ?
This is a specific docker image so it maybe doable for me to get a working version !

**Comment by qmfrederik** [comment]
Sorry, I know very little about Azure Functions. You can try to install libgdiplus on an OS which is similar to whathever OS Azure Functions is using, and copying the libgdiplus binaries (including all dependencies) to your Azure Functions app. Sounds like an uphill battle to me.
